// <auto-generated />
namespace p4_projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RestaurantMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestaurantMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202403211404550_RestaurantMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
