//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p4_projekt.tabele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restauracje
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
    }
}
